package com.automation.mobile.entities;

public interface BannerConfType {
    /**
     * standard banner app configuration.
     */
    String ACTIVITY_NAME = "activityName";
    String PACKAGE_NAME = "packageName";
    String BUNDLE_ID = "bundleId";

    /**
     * banner related account information
     */
    String BANNER_SNAP2USERNAME = "USERNAME_SNAP2";
    String BANNER_SNAPUSERNAME = "USERNAME_SNAP";
    String BANNER_EXISTINGUSERNAME = "USERNAME_EXISTING";
    String BANNER_MFAUSERNAME = "USERNAME_MFA";
    String BANNER_ZIPCODE = "ZIPCODE";
    String REWARDS_ZIPCODE = "ZIPCODE_REWARDS";
    String NOREWARDS_ZIPCODE = "ZIPCODE_NOREWARDS";
    String KIOSK_ZIPCODE = "ZIPCODE_KIOSK";
    String COA_ZIPCODE = "ZIPCODE_COA";
    String BANNER_PRODUSERNAME = "USERNAME_PROD";


    String BANNER_INSTOREZIPCODE = "ZIPCODE_INSTORE";

    String BANNER_USERNAME = "USERNAME";
    String BANNER_PASSWORD = "PASSWORD";
    String BANNER_CONTACT_NUMBER = "CONTACTNUMBER";
    String BANNER_PHONE_NUMBER = "PHONENUMBER";
    String BANNER_FIRST_NAME = "FIRSTNAME";
    String BANNER_LAST_NAME = "LASTNAME";
    String BANNER_ADDRESS_LINE1 = "ADDRESSLINE1";
    String BANNER_ADDRESS_LINE2 = "ADDRESSLINE2";
    String BANNER_ADDRESS_LINE1_FORSR = "ADDRESSLINE1FORSR";
    String BANNER_ADDRESS_LINE = "ADDRESSLINE";

    String BANNER_ZIPCODE_DIFF = "ZIPCODE_DIFF";

    String BANNER_ADDRESS_LINE2_FORSR = "ADDRESSLINE2FORSR";
    String BANNER_ADDRESS_LINE3_FORSR = "ADDRESSLINE3FORSR";
    String BANNER_ADDRESS_LINE4_FORSR = "ADDRESSLINE4FORSR";
    String BANNER_ADDRESS_LINE5_FORSR = "ADDRESSLINE5FORSR";
    String BANNER_ADDRESS_LINE6_FORSR = "ADDRESSLINE6FORSR";
    String BANNER_ADDRESS_LINE7_FORSR = "ADDRESSLINE7FORSR";
    String BANNER_ADDRESS_LINE8_FORSR = "ADDRESSLINE8FORSR";
    String BANNER_ADDRESS_LINE9_FORSR = "ADDRESSLINE9FORSR";
    String BANNER_ADDRESS_LINE10_FORSR = "ADDRESSLINE10FORSR";
    String BANNER_ADDRESS_LINE11_FORSR = "ADDRESSLINE11FORSR";
    String BANNER_ADDRESS_LINE12_FORSR = "ADDRESSLINE12FORSR";
    String BANNER_ADDRESS_LINE13_FORSR = "ADDRESSLINE13FORSR";
    String BANNER_ADDRESS_LINE14_FORSR = "ADDRESSLINE14FORSR";


    // Below entities are for Flip weekly ad flow
    String FLIP_WEEKLY_AD_PRODUCT_PRICE = "FlipWeeklyAdProductPrice";
    String FLIP_WEEKLY_AD_PRODUCT_NAME = "FlipWeeklyAdProductName";
    String FLIP_WEEKLY_AD_PRODUCT_DESC = "FlipWeeklyAdProductDesc";
    String FLIP_WEEKLY_AD_VALID_DATE = "FlipWeeklyAdValidDate";
    String FLIP_WEEKLY_AD_ADDRESS = "FlipWeeklyAdAddress";
}
